[package]
name = "abstraction"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-atomic = { version = "1.7.0", features = ["float"] }
rand = "0.8.5"
rayon = "1.10.0"
smallvec = "1.13.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "k_means_bench"
harness = false
