[package]
name = "abstraction"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
smallvec = "1.13.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "k_means_bench"
harness = false